### ISSUE TITLE
Is it possible to debug the programes on 24G GPU?

### ISSUE THREAD

**Issue by JunyuanDeng** [OpenDriveLab/Vista#12]
Hello,

I want to debug the training process on 24G GPU then train it on larger GPUs, is it possible to do that?

I try to set the target_height and width to 64:
```
data:
  target: vwm.data.dataset.Sampler
  params:
    batch_size: 1
    num_workers: 16
    subsets:
      - NuScenes
    probs:
      - 1
    samples_per_epoch: 16000
    target_height: 64
    target_width: 64
    num_frames: *num_frames
```

But it still run OOM,

Thanks in advance for your help!
